version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/.api/apis/codecov"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
