version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/.api/apis/codecov"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    groups:
      vitest:
        patterns:
          - "@vitest/coverage-v8"
          - "vitest"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
