version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/.api/apis/codecov"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    ignore:
      - dependency-name: "@types/node"
        versions:
          - "19.x"
          - "20.x"
          - "21.x"
          - "22.x"
          - "23.x"
          - "24.x"
          - "25.x"
          - "26.x"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
