name: 'slack-health-score'
description: 'Report some code quality heuristics as defined by Slack Engineering'
inputs:
  extension:
    description: 'File extension of files to filter on to search for problematic comments. E.g. "js" or "go"'
    required: true
  github_token:
    description: 'A GitHub access token with permissions to write commit statuses. Recommended to set this to `secrets.GITHUB_TOKEN`.'
    required: true
  codecov_token:
    description: 'A CodeCov access token with read permissions to the repo. Setting this will try to pull coverage information for the repo from CodeCov to include in health score calculation.'
    required: false
  include:
    description: 'Only parse the specified files and directories (recursively). Ideally supports glob syntax? Defaults to contents of `.`. E.g. "src"'
    required: false
  exclude:
    description: 'Ignore the specified files and directories. Essentially a direct argument into `find` `-not -path "{arg}"`. Defaults to contents of `.gitignore`. E.g. "node_modules"'
    required: false
# outputs:
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'heart'
  color: 'red'
